export const sampleQuestions = [
  {
    id: 'q1', title: 'Is this email from "Google" about a security breach real or a scam?', slug: 'google-security-breach-email-scam',
    content: 'I received an email saying my Google account was breached and I need to click a link to secure it. Is this legit?',
    status: 'OPEN', viewCount: 342, voteCount: 12, answerCount: 3, tags: ['scam', 'email', 'google', 'security'],
    isResolved: true, createdAt: new Date().toISOString(),
    author: { id: 'u1', name: 'John M.', avatar: '', trustScore: 65 },
    category: { name: 'Online Safety', slug: 'online-safety' },
  },
  {
    id: 'q2', title: 'Has anyone actually made money with print-on-demand?', slug: 'print-on-demand-real-experience',
    content: 'I keep seeing ads about Printful and Printify. Is this actually profitable or just another hype?',
    status: 'OPEN', viewCount: 521, voteCount: 24, answerCount: 7, tags: ['business', 'ecommerce', 'print-on-demand'],
    isResolved: false, createdAt: new Date().toISOString(),
    author: { id: 'u2', name: 'Grace T.', avatar: '', trustScore: 72 },
    category: { name: 'Business', slug: 'business' },
  },
  {
    id: 'q3', title: 'Best online learning platforms for programming in Rwanda?', slug: 'best-online-learning-programming-rwanda',
    content: 'I want to learn programming but there are so many platforms. Which ones work well in Rwanda without internet issues?',
    status: 'OPEN', viewCount: 287, voteCount: 18, answerCount: 5, tags: ['education', 'programming', 'rwanda'],
    isResolved: true, createdAt: new Date().toISOString(),
    author: { id: 'u3', name: 'Patrick N.', avatar: '', trustScore: 55 },
    category: { name: 'Education', slug: 'education' },
  },
  {
    id: 'q4', title: 'Is cryptocurrency investment still worth it?', slug: 'cryptocurrency-investment-worth-it',
    content: 'With all the ups and downs, is crypto still a good investment? Looking for honest opinions.',
    status: 'OPEN', viewCount: 654, voteCount: 31, answerCount: 12, tags: ['finance', 'crypto', 'investment'],
    isResolved: false, createdAt: new Date().toISOString(),
    author: { id: 'u4', name: 'Alice K.', avatar: '', trustScore: 80 },
    category: { name: 'Finance', slug: 'finance' },
  },
  {
    id: 'q5', title: 'How to identify a legitimate scholarship opportunity?', slug: 'identify-legitimate-scholarship',
    content: 'I see many scholarship posts on social media. How do I know which ones are real and which are scams?',
    status: 'OPEN', viewCount: 431, voteCount: 27, answerCount: 8, tags: ['scholarships', 'scams', 'education'],
    isResolved: true, createdAt: new Date().toISOString(),
    author: { id: 'u5', name: 'David R.', avatar: '', trustScore: 68 },
    category: { name: 'Scholarships', slug: 'scholarships' },
  },
  {
    id: 'q6', title: 'Freelancing vs remote job: which is better for beginners?', slug: 'freelancing-vs-remote-job-beginners',
    content: 'Should I start with freelancing on Fiverr/Upwork or look for a remote job? What\'s the better path for someone starting out?',
    status: 'OPEN', viewCount: 389, voteCount: 15, answerCount: 6, tags: ['freelancing', 'jobs', 'career'],
    isResolved: false, createdAt: new Date().toISOString(),
    author: { id: 'u6', name: 'Sarah M.', avatar: '', trustScore: 71 },
    category: { name: 'Jobs', slug: 'jobs' },
  },
];
